In [1]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


In [2]:
zeros_array = np.zeros((2, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
ones_array = np.ones((2, 3))
print(ones_array)


[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
range_array = np.arange(0, 10, 2)
print(range_array)


[0 2 4 6 8]


In [5]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)


[0.   0.25 0.5  0.75 1.  ]


In [6]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
reshaped_array = np.reshape(np.arange(8), (2, 4))
print(reshaped_array)


[[0 1 2 3]
 [4 5 6 7]]


In [8]:
flattened_array = np.ravel(reshaped_array)
print(flattened_array)


[0 1 2 3 4 5 6 7]


In [9]:
transposed_array = np.transpose(reshaped_array)
print(transposed_array)


[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [10]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
concatenated_array = np.concatenate((array1, array2), axis=0)
print(concatenated_array)


[[1 2]
 [3 4]
 [5 6]]


In [11]:
a = np.array([1, 2])
b = np.array([3, 4])
sum_array = np.add(a, b)
print(sum_array)


[4 6]


In [12]:
diff_array = np.subtract(a, b)
print(diff_array)


[-2 -2]


In [13]:
prod_array = np.multiply(a, b)
print(prod_array)


[3 8]


In [14]:
div_array = np.divide(a, b)
print(div_array)


[0.33333333 0.5       ]


In [15]:
dot_product = np.dot(a, b)
print(dot_product)


11


In [16]:
sqrt_array = np.sqrt(a)
print(sqrt_array)


[1.         1.41421356]


In [17]:
exp_array = np.exp(a)
print(exp_array)


[2.71828183 7.3890561 ]


In [18]:
mean_value = np.mean(arr)
print(mean_value)


2.0


In [19]:
median_value = np.median(arr)
print(median_value)


2.0


In [20]:
std_value = np.std(arr)
print(std_value)


0.816496580927726


In [21]:
var_value = np.var(arr)
print(var_value)


0.6666666666666666


In [22]:
random_array = np.random.rand(2, 3)
print(random_array)


[[0.77833748 0.81946449 0.11424832]
 [0.27102153 0.92175052 0.17423512]]


In [23]:
random_normal_array = np.random.randn(2, 3)
print(random_normal_array)


[[-0.95016017  1.35834371  1.51435271]
 [ 0.85465728  0.26458779 -0.96123529]]


In [24]:
random_integers = np.random.randint(0, 10, (2, 3))
print(random_integers)


[[1 7 3]
 [2 0 2]]


In [25]:
element = arr[1]
print(element)


2


In [26]:
sub_array = arr[0:2]
print(sub_array)


[1 2]


In [27]:
bool_index_array = arr[arr > 1]
print(bool_index_array)


[2 3]


In [28]:
matrix = np.array([[1, 2], [3, 4]])
inv_matrix = np.linalg.inv(matrix)
print(inv_matrix)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
eigvals, eigvecs = np.linalg.eig(matrix)
print(eigvals)
print(eigvecs)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
